### ISSUE TITLE
kind of help ?

### ISSUE THREAD

**Issue by PK70499** [homotechsual/NinjaRMM#1]
Hello,

i have  done the setup as described. Running PS 7. But if i use the command with my own values like: 
"Connect-NinjaRMM -Instance 'eu' -ClientID 'ABCDEfGH-IjKLmnopqrstUV1w23x45yz' -ClientSecret 'abc123abc123def456def456ghi789ghi789lmn012lmn012' -Port 9090 -UseWebAuth -ShowTokens"  i only reach an error from Ninja with contains: 

![grafik](https://user-images.githubusercontent.com/56996770/131792870-1e57d32a-a420-46f1-b30d-a751155d5717.png)

Any suggestions?

localhost config is done by  setup the basics in Ninja, tested local, it is reachable and it shows me the result:
ERROR: Unable to retrieve authorisation code.

**Comment by homotechsual** [comment]
Hi @PK70499 404 is an interesting result. Are you able to show me the output of `Get-Error` (removing anything confidential in the output?)

**Comment by PK70499** [comment]
> 
> 
> Hi @PK70499 404 is an interesting result. Are you able to show me the output of `Get-Error` (removing anything confidential in the output?)



Hello @homotechsual 
i have executed the friendly ps  command again,  same error message as above, but  on "get-error"  i receive nothing....
returning blinking cursor.

And yes, i use PS7

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

can i do more ?

**Comment by PK70499** [comment]
![grafik](https://user-images.githubusercontent.com/56996770/131953377-1f98865f-5cb4-4f4b-bb96-9a87e0dcb253.png)

![grafik](https://user-images.githubusercontent.com/56996770/131953411-3889cd0c-3637-4d9e-9c07-68cec54a6b8c.png)

**Comment by homotechsual** [comment]
Can you confirm the settings you used for your NinjaRMM API application. It should look like this:
![image](https://user-images.githubusercontent.com/2288257/131977617-9bebce71-98d1-4430-9c98-129ea190486a.png)

**Comment by homotechsual** [comment]
This allows NinjaRMM to redirect you to the small local web server that then handles the rest of the auth flow. This won't be needed after 5.3 :-)

**Comment by PK70499** [comment]
yes, it is the same

![grafik](https://user-images.githubusercontent.com/56996770/131993891-fcf3266b-c586-4ec3-93a5-8b82adb74f83.png)

**Comment by PK70499** [comment]
solved.. the error was: "/"  is missing on the end of localhost entry.
Correct it must be: "http://localhost:9090**/**"
If  you use "http://localhost:9090" -  it goes on the knwon error.
