### ISSUE TITLE
Does not want to connect.

### ISSUE THREAD

**Issue by duffman36** [homotechsual/NinjaRMM#3]
Hi. 

So I am very very green on the API Webcalls but i followed the guide to a T but i get the following error.

{ "resultCode": "FAILURE", "errorMessage": "HTTP 404 Not Found", "incidentId": "WEB_MGMT_SERVICE-1a-1631107956-UGUBDHNX" }

Think its something to do with the redirect URI but not sure what it is.

Thanks

**Comment by homotechsual** [comment]
Is this the same as #1? Missing `/` at the end of the redirect URI in NinjaRMM settings?

**Comment by duffman36** [comment]
Yeah sorry i took a look at the issues but did not see anything only after posting. 

Thanks for the quick response appreciate it!

**Comment by homotechsual** [comment]
I'll add a note to the README to clarify :-)

**Comment by duffman36** [comment]
I see in the readme it does not specify to add a trailing /

Only shows the redirect uri.

But its cool no worries.

**Comment by homotechsual** [comment]
Yup, that'll be fixed in a second along with a new release today :-)

**Comment by duffman36** [comment]
i am guessing the below is a date of some sort?

created          : 1624014024,761
lastContact      : 1631110371,339
lastUpdate       : 1631110372

How is it structured? like ddmmyyyy or what? it does not make sense to me lol
