### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by knoeblsn** [homotechsual/NinjaRMM#5]
Hello,

I think I followed all the steps from the ReadMe, but I still get an error when running the Connect-NinjaRMM CMDLet:

> PS C:\Users\username> Connect-NinjaRMM @ConnectionParameters

> New-NinjaRMMError: C:\Users\username\OneDrive - company\Dokumente\PowerShell\Modules\NinjaRMM\0.1.0\Public\Connect-NinjaRMM.ps1:132
> Line |
>  132 |              New-NinjaRMMError @ErrorRecord
>     |                                ~~~~~~~~~~~~
>     | Cannot process argument transformation on parameter 'ErrorRecord'. Cannot convert the "The term
>      | 'dotnet' is not recognized as a name of a cmdlet, function, script file, or executable program. Check
>     | the spelling of the name, or if a path was included, verify that the path is correct and try again."
>      | value of type "System.Management.Automation.ErrorRecord" to type "System.Exception".

PS Version is 7:

>  PS C:\Users\username> get-host | select version
>  Version
>  -------
>  7.1.4

Do you have any idea whats the reason?

Greetings from Germany

**Comment by homotechsual** [comment]
Sounds like it can't find the dotnet runtime used for the small webserver (required until 5.3 adds proper `client_credentials` auth).

**Comment by knoeblsn** [comment]
Thanks for the hint, I was able to resolve the issue after installing .NET as advised here:

https://docs.microsoft.com/en-us/dotnet/core/install/windows?tabs=net50

**Comment by homotechsual** [comment]
I'll get that added to the README :-0
